baseURL: "https://tianalei.github.io/personal-blog/"
title: "Tian's Blog"
theme: "PaperMod"

# 语言设置
languageCode: "zh-cn"
defaultContentLanguage: "zh-cn"

# 基础设置
paginate: 10
summaryLength: 70

# 主题设置
params:
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowPostNavLinks: true

  homeInfoParams:
    Title: "Tian"
    Content: "Tian's Blog"

  socialIcons:
    - name: github
      url: "https://github.com/tianalei"
  mainSections:
    - posts


# 菜单设置
menu:
  main:
    - identifier: categories
      name: category
      url: /categories/
      weight: 10
    - identifier: tags
      name: tag
      url: /tags/
      weight: 20
    - identifier: archives
      name: archives
      url: /archives/
      weight: 30
    - identifier: gadgets
      name: gadgets
      url: /gadgets/
      weight: 40
    - identifier: search
      name: search
      url: /search/
      weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON